### ISSUE TITLE
Railway is damaged and cannot be. You should move it to the Bin.

### ISSUE THREAD

**Issue by czepluch** [Railway-Wallet/Railway-Wallet-Desktop#5]
When trying to install railway-mac-arm64.dmg on an m1 macbook I get the error in the issue description. Looks like the dmg is broken or something like that. Is there a fix for this or should I just wait for the next release?

**Comment by ethermachine** [comment]
Try the Railway-mac-x64.dmg. Worked for me

**Comment by PerfectSense1** [comment]
> Try the Railway-mac-x64.dmg. Worked for me

Thanks, it works indeed

**Comment by czepluch** [comment]
It seems that the last two releases don't even include Mac assets.

**Comment by ethermachine** [comment]
> It seems that the last two releases don't even include Mac assets.

they have it: [Railway-mac-x64.dmg](https://github.com/Railway-Wallet/Railway-Wallet-Desktop/releases/download/v5.14.23/Railway-mac-x64.dmg)

**Comment by czepluch** [comment]
Yeah, it's there now. And as of https://github.com/Railway-Wallet/Railway-Wallet-Desktop/releases/tag/v5.14.27 it also works for Mac again.
